export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAER_ERRORS';
export const SET_ALERT ="SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const GET_HEATMAP_FROM_DATA = "GET_HEATMAP_FROM_DATA"
export const GET_HEATMAP_TO_DATA = "GET_HEATMAP_TO_DATA"
export const DATA_FETCH_ERROR = "DATA_FETCH_ERROR"
export const GET_DEPARTURE_RANKING = "GET_DEPARTURE_RANKING"
export const GET_DESTINATION_RANKING = "GET_DESTINATION_RANKING"
export const GET_TIME_REQUESTS = "GET_TIME_REQUESTS"
export const GET_TIME_CALENDAR = "GET_TIME_CALENDAR"
export const GET_GENERAL_DATA ="GET_GENERAL_DATA"

